<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.ZvyaginaNY.Sprint5.Task6.V14.Lib\Tyuiu.ZvyaginaNY.Sprint5.Task6.V14.Lib.csproj" />
  </ItemGroup>

</Project>
